#!/usr/bin/env bash
set -euo pipefail

platform=$(uname -ms)

case $platform in
'Darwin x86_64')
    target=darwin-x64
    ;;
'Darwin arm64')
    target=darwin-arm64
    ;;
'Linux aarch64' | 'Linux arm64')
    target=linux-arm64
    ;;
'Linux x86_64')
    target=linux-x64
    ;;
*)
    echo "unsupported platform" >&2
    exit 1
    ;;
esac

curl -fso /usr/local/bin/bermuda https://github.com/bermudabay/bin/releases/latest/download/bermuda-$target
chmod +x /usr/local/bin/bermuda