#!/usr/bin/env bash

set -eEo pipefail

version=${VERSION:-v0.0.0}
dir=$HOME/.bermudabay/bin
bin=$dir/bermuda

case $(uname -ms) in
'Darwin x86_64')
    target=darwin-x64
    ;;
'Darwin arm64')
    target=darwin-arm64
    ;;
'Linux aarch64' | 'Linux arm64')
    target=linux-arm64
    ;;
'Linux x86_64')
    target=linux-x64
    ;;
*)
    echo "unsupported platform" >&2
    exit 1
    ;;
esac

curl -fsSLo $bin https://github.com/BermudaBay/bin/releases/download/$version/bermuda-$target
chmod +x $bin
echo "installed at $bin"

if [[ ":$PATH:" != *":$dir:"* ]]; then
  echo "export PATH=\"\$PATH:$dir\"" >> ~/.profile
  echo -e "to use bermuda in existing shells run:\nsource ~/.profile" 
fi
